rosbag record --split --size=500 -b 4096 \
/tf \
/uav1/mavros/local_position/pose \
/uav1/mavros/local_position/velocity_local \
/uav1/mavros/setpoint_velocity/cmd_vel  \
/uav1/Mission \
/uav1/image_raw \
/uav1/GoalAction \
/uav1/mavros/global_position/local \
/uav1/mavros/global_position/gp_vel \
/uav1/mavros/global_position/rel_alt \
/uav1/mavros/global_position/compass_hdg \
/uav1/mavros/global_position/raw/fix \
/uav1/mavros/global_position/raw/gps_vel \
/uav1/mavros/state \
/uav1/mavros/battery \
/uav1/detection \
/uav1/distance_estimation \
/uav2/mavros/local_position/pose \
/uav2/mavros/local_position/pose_cov \
/uav2/mavros/local_position/velocity_local \
/uav2/mavros/setpoint_velocity/cmd_vel  \
/uav2/Mission \
/uav2/image_raw \
/uav2/GoalAction \
/uav2/mavros/global_position/local \
/uav2/mavros/global_position/gp_vel \
/uav2/mavros/global_position/rel_alt \
/uav2/mavros/global_position/compass_hdg \
/uav2/mavros/global_position/raw/fix \
/uav2/mavros/global_position/raw/gps_vel \
/uav2/mavros/state \
/uav2/mavros/battery \
/uav2/detection \
/uav2/distance_estimation \
/vis/uav_path \
/vis/uav_pos \
/vis/uav_tar \
/vis/uav_pred \
/camera/color/image_raw/compressed \
/debug_image \
/uav1/prediction_debug \
/uav1/detection_debug
