rosbag record --split --size=500 -b 3000 \
/clicked_point \
/diagnostics \
/rosout \
/rosout_agg \
/tf \
/tf_static \
/uav1/dist_to_target \
/uav1/gimbal_pose \
/uav1/mavros/local_position/odom \
/uav1/mavros/local_position/velocity_body \
/uav1/mavros/rc/in \
/uav1/mavros/setpoint_accel/accel \
/uav1/mavros/setpoint_attitude/cmd_vel \
/uav1/mavros/setpoint_attitude/thrust \
/uav1/mavros/setpoint_position/local \
/uav1/mavros/setpoint_velocity/cmd_vel \
/uav1/mavros/state \
/uav1/mission \
/uav1/pointcloud \
/uav1/tracking_guidance/cmd_vel \
/uav1/trajectory_prediction/bbox_center \
/uav1/trajectory_prediction/bbox_center_dist \
/uav1/trajectory_prediction/target/positions \
/uav1/trajectory_prediction/target/trajectory/future_path \
/uav1/trajectory_prediction/target/trajectory/past \
/uav2/odom \
/yolov7/yolov7 \
/yolov7/yolov7/visualization \
/zed2i/zed_node/confidence/confidence_map \
/zed2i/zed_node/depth/camera_info \
/zed2i/zed_node/depth/depth_registered/compressedDepth \
/zed2i/zed_node/depth/depth_registered/compressedDepth/parameter_descriptions \
/zed2i/zed_node/depth/depth_registered/compressedDepth/parameter_updates \
/zed2i/zed_node/left/camera_info \
/zed2i/zed_node/left/image_rect_color/compressed \
/zed2i/zed_node/left/image_rect_color/compressed/parameter_descriptions \
/zed2i/zed_node/left/image_rect_color/compressed/parameter_updates \
/zed2i/zed_node/parameter_descriptions \
/zed2i/zed_node/parameter_updates \
/zed2i/zed_node/point_cloud/cloud_registered \
